version: "3.9"

services:
    promptfoo-ui:
        #image: promptfoo-ui
        build:
            context: "."
            args:
                NEXT_PUBLIC_PROMPTFOO_BASE_URL: http://localhost:3000
        ports:
            - 3000:3000
        #environment:
        #    - "true"
        #    - OPENAI_API_KEY=sk-1234
        volumes:
            - ./local_promptfoo:/root/.promptfoo

